CREATE TABLE SERVICO
( CODIGO INTEGER,
DESCR VARCHAR(20),
VAL_M2 FLOAT,
DUR_M2 TIME,
PRIMARY KEY(CODIGO)
);


CREATE TABLE EMPREGADO
( MATRICULA INTEGER PRIMARY KEY,
NOME VARCHAR(20)
);

CREATE TABLE PF
( COD INT PRIMARY KEY,
CPF TEXT,
NOME VARCHAR(20),
LOG TEXT,
COMPLEMENTO TEXT,
UF TEXT,
MUNICIPIO TEXT,
BAIRRO TEXT,
CEP TEXT
);

CREATE TABLE PJ
( COD INT PRIMARY KEY,
CPF TEXT,
NOME VARCHAR(20),
LOG TEXT,
COMPLEMENTO TEXT,
UF TEXT,
MUNICIPIO TEXT,
BAIRRO TEXT,
CEP TEXT
);

CREATE TABLE TELEFONE
( ID INT,
TIPO CHAR(11) CHECK (TIPO IN('CEL', 'RES')),
NUM CHAR(11) NOT NULL,
COD_PF INT REFERENCES PF(COD), PRIMARY KEY(ID)